<!DOCTYPE html>
<html>
  <head>
    <title>Jerry's Hot Rods</title>
    <meta name="theme-color" content="#ffffff">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="favicon.ico" type="image/x-icon" />
    <link href='http://fonts.googleapis.com/css?family=Arizonia' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css" />
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css" />
    {% if isProd %}
      <link rel="stylesheet" type="text/css" href="/assets/styles.css">
    {% endif %}

  </head>
  <body>
    <div id="jhrSite">
      <noscript>
          <p>
          Sorry, the Flood Information Viewer requires Javascript to function.
          </p>
      </noscript>
    </div>
    <script src="assets/app.bundle.js" type="text/javascript"></script>
  </body>
</html>
